import Head from "next/head";
import { useState } from "react";
import axios from "axios";


export default function Home() {

// Declarar uma nova variavel com state e atribuir o objeto
const [data, setData] = useState({name:'',
  email:''
});

// Receber os dados dos campos do formulario
const valueInput = (e) => setData({...data, [e.target.name]: e.target.value});

// Executar a função quando o usuário clicar no botão do formulário
const addUser = (e) => {

  //Bloquear o recarregamento da pagina
  e.preventDefault();
  console.log('Enviar para api');
  console.log(data.name)
  console.log(data.email);
}

  return (
    <>
      <Head>
        <title>Cadastro de Usuário no Banco de Dados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Cadastrar Usuário</h2>

        <form onSubmit={addUser}>
          <label>Nome: </label>
          <input type="text" name="name" placeholder="Digite seu nome" onChange={valueInput} value={data.name} />

          <label>E-mail: </label>
          <input type="email" name="email" placeholder="Digite seu e-mail" onChange={valueInput} value={data.email} />

          <button type="submit">Enviar</button>
        </form>
      </main>
    </>
  );
}
