import Head from "next/head";
import { useState } from "react";
import axios from "axios";


export default function Home() {

// Declarar uma nova variavel dados com state e atribuir o objeto
const [data, setData] = useState({
  name:'',
  email:''
});

// Declarar a variavel para receber a mensagem
const [message, setMessage] = useState("");

// Receber os dados dos campos do formulario
const valueInput = (e) => setData({...data, [e.target.name]: e.target.value});

// Executar a função quando o usuário clicar no botão do formulário
const addUser = async (e) => {

  //Bloquear o recarregamento da pagina
  e.preventDefault();
  //console.log('Enviar para api');
  //console.log(data.name)
  //console.log(data.email);


const headers = {
  'headers': {
    //Indica que os dados serão enviados em formato de objeto
    'Content-Type': 'application/json'
  }
};

// Faz a requisição para o servidor com o axios, indicando o metodo, o endereço, e envia os dados do formulario e o cabeçalho
await axios.post('http://localhost:8080/users', data, headers)
  .then((response) => {
    //console.log(response.data.mensagem)

    //Atribuir a mensagem no state message
    setMessage(response.data.mensagem);

    // Limpar os dados do state e os dados dos campos do formulario
    setData({
      name: '',
      email: ''
    });
  }).catch((err) => {
    //console.log(err.response.data.mensagem)
    if(err.response) {
      setMessage(err.response.data.mensagem)
    } else {
      setMessage("Erro: Tente novamente mais tarde ou entre em contato com o admin!")
    }
});

};
  return (
    <>
      <Head>
        <title>Cadastro de Usuário no Banco de Dados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Cadastrar Usuário</h2>

        {message ? <p>{message}</p> : ""}

        <form onSubmit={addUser}>
          <label>Nome: </label>
          <input type="text" name="name" placeholder="Digite seu nome" onChange={valueInput} value={data.name} />

          <label>E-mail: </label>
          <input type="email" name="email" placeholder="Digite seu e-mail" onChange={valueInput} value={data.email} />

          <button type="submit">Enviar</button>
        </form>
      </main>
    </>
  );
}
